[package]
name = "anexpia/bufferencoder"
description = "A very efficient and simple-to-use encoder that turns tables into buffers."
license = "GPL-3.0"
version = "1.4.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
